version: '3.4'

services:
  seestarvarstarrun:
    image: seestarvarstarrun
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 seestar_varstar_params.py "]
    ports:
      - 5678:5678
